### ISSUE TITLE
Class "myCompany\humhub\modules\example\humhub\components\Module" not found

### ISSUE THREAD

**Issue by antontranelis** [humhub-contrib/devtools#24]
Sorry for this noob question. I'm really new to php:

If I use devtools to generate a module and load the output in HumHub without touching the code, I always get an error like that 

`
Class "myCompany\humhub\modules\example\humhub\components\Module" not found
`

How to fix that?

**Comment by luke-** [comment]
What is the `namespace` of your `Module.php` class? Did you changed the namespaces using the provided script?

**Comment by antontranelis** [comment]
I did not touch the namespace. It's `myCompany\humhub\modules\example`

**Comment by antontranelis** [comment]
I don't know, what script to use for the namespace

**Comment by luke-** [comment]
Ok, I would recommend this as module boilerplate:
https://github.com/humhub/example-basic

**Comment by antontranelis** [comment]
that is working. Thank you 👍

**Comment by antontranelis** [comment]
I found the solution for the devtools approach. To Make the devtools generated code work I had to change 

```
   ...
class Module extends humhub\modules\content\components\ContentContainerModule
{
   ...
}
```
to
```
   ...
use humhub\modules\content\components\ContentContainerModule;
class Module extends ContentContainerModule
{
   ...
}
```

**Comment by 001101** [comment]
please don't spam github with basic learning stuff
